Emcs 81 adding mongo db
hmrc/excise-movement-control-system-api pull request #11
Opened 2023-09-25 16:04 UTC by solomonamadi

2023-09-26 12:00 UTC, mauro-fanton commented on app/uk/gov/hmrc/excisemovementcontrolsystemapi/services/MovementMessageService.scala
> +  def saveMovementMessage(localReferenceNumber: String, consignorId: String, consigneeId: String): Future[CreateMovementMessageResult] = {
I would handle the mongo DB error here:
```suggestion
def saveMovementMessage(movementMessage: MovementMessage): Future[Either[MongoError, MovementMessage]] = {
    movementMessageRepository.saveMovementMessage(movementMessage)
      .map(_ => Right(movementMessage))
      .recover{
        case ex: Throwable => Left(MongoError(ex.getMessage))
      }
  }
```

2023-09-26 12:12 UTC, mauro-fanton commented
MovementMessageRepository make the test fail. This should be mocked.

2023-09-29 10:57 UTC, ChrisCookOC requested changes

2023-09-29 10:57 UTC, ChrisCookOC commented on test/uk/gov/hmrc/excisemovementcontrolsystemapi/connector/MovementMessageConnectorSpec.scala
> +      result.left.value mustBe InternalServerError(s"""{"dateTime":"2023-09-17T09:32:50.345","message":"Exception","debugMessage":"error","emcsCorrelationId":"$emcsCorrelationId"}""")
Do we have an object we can use to create this? Just might be easier if we change things

2023-09-29 14:19 UTC, ChrisCookOC approved these changes

2023-09-29 14:32 UTC, merged