EMCS-820 - Add correlationID in header and display it in Kibana
hmrc/excise-movement-control-system-api pull request #253
Opened 2024-12-11 13:16 UTC by nemanjatomanovic

2024-12-12 12:52 UTC, oliverslade commented on app/uk/gov/hmrc/excisemovementcontrolsystemapi/services/CorrelationIdService.scala
>    def generateCorrelationId(): String = UUID.randomUUID().toString
this either doesnt need brackets on it or the call on line 36 needs brackets adding

2024-12-12 12:54 UTC, oliverslade commented on app/uk/gov/hmrc/excisemovementcontrolsystemapi/controllers/AdminDetailsController.scala
> +  correlationIdService: CorrelationIdService
looks like this is injected but never used?

2024-12-12 12:58 UTC, oliverslade commented on app/uk/gov/hmrc/excisemovementcontrolsystemapi/controllers/PreValidateTraderController.scala
> +  correlationIdService: CorrelationIdService
In the PreValidateTraderConnector it still generates a new correlationId, is that correct?

2024-12-12 13:09 UTC, oliverslade requested changes

2024-12-12 13:09 UTC, oliverslade commented on app/uk/gov/hmrc/excisemovementcontrolsystemapi/services/SubmissionMessageService.scala
> +      .getOrElse(correlationIdService.generateCorrelationId())
line break between these code blocks might help with readability

2024-12-13 12:09 UTC, Froom2 approved these changes

2024-12-13 13:43 UTC, oliverslade approved these changes

2024-12-13 14:01 UTC, merged